- package.json
- src/loader.js
- src/traverse.js
- test/fixtures/example.js
- yarn.lock
> update parser stuff

- example/src/Button.js
- src/runtime/styled.js
Fixes https://github.com/4Catalyzer/css-literal-loader/issues/27
> Fix deleting boolean props

- README.md
> Add @keyframes docs

- README.md
> Fix keyframes example

- .eslintrc
- README.md
- package.json
- src/runtime/styled.js
- test/setup.js
- test/styled.test.js
- yarn.lock
> add 'as' prop

- README.md
> Update first paragraph

- README.md
I made a little something! ✨
I wasn't sure where to put it, is here ok?
> Add gatsby-plugin-astroturf to readme

- src/loader.js
- src/plugin.js
- test/__snapshots__/loader.test.js.snap
- test/__snapshots__/plugin.test.js.snap
- test/fixtures/imports-css.js
- test/fixtures/imports-mixed.js
saves some bytes in the output
> remove unused css imports

- css-loader.js
- loader.js
- package.json
- src/VirtualModulePlugin.js
- src/loader.js
- src/memory-fs.js
- src/proxyFileSystem.js
- yarn.lock
Allows for better caching by webpack
> feat: support file times for virtual files

- README.md
Close https://github.com/4Catalyzer/astroturf/issues/109 and https://github.com/4Catalyzer/astroturf/issues/108
> Add Parcel and Preact support to docs

- src/css-loader.js
> fix: made options compatible with css-loader@2.0.0

- src/plugin.js
- src/runtime/styled.js
- test/__snapshots__/loader.test.js.snap
- test/__snapshots__/plugin.test.js.snap
- test/fixtures/with-props.js
- test/styled.test.js
- types/index.d.ts
- types/test.tsx
ZERO idea if the types are sound, it's mostly a munging of what DT has for styled-components.
> feat: add attrs api

- src/plugin.js
- src/runtime/styled.js
- src/utils/normalizeAttrs.js
- test/__snapshots__/loader.test.js.snap
- test/__snapshots__/plugin.test.js.snap
- test/styled.test.js
allows hook usage in the plain object case
> feat: always compile attrs to a function

- src/plugin.js
- src/runtime/styled.js
- test/__file_snapshots__/integration-js.js
- test/__file_snapshots__/loader__css-prop.js
- test/__file_snapshots__/loader__typescript.tsx
- test/__file_snapshots__/plugin__css-prop.js
- test/integration/main.js
- test/loader.test.js
the TS preset will confuse the React import as "types only" so we need to reexport Fragment :/
> fix: fragments in typescript

- src/loader.js
- test/helpers.js
- test/integration.test.js
Still geting false positives sometimes. Unclear why, doesn't seem knowable
> feat: only warn on possible cycle

- package.json
- src/features/css-prop.js
- test/__file_snapshots__/loader__css-prop.js
- test/__file_snapshots__/loader__typescript.tsx
- test/__file_snapshots__/plugin__css-prop.js
- test/css-prop.test.js
- test/custom-properties.test.js
- test/loader.test.js
- yarn.lock
BREAKING CHANGE: changes the import order for styles which affects the cascade (should be correct now)
> fix: inline css prop requires so they are in the correct order

- example/.babelrc
- example/package.json
- example/yarn.lock
Fixes https://github.com/4Catalyzer/astroturf/issues/540
> docs: Fix example

- CHANGELOG.md
- package.json
> chore: Fix package.json

- src/loader.ts
- src/utils/buildTaggedTemplate.ts
- src/utils/replaceComposes.ts
- src/utils/resolveDependency.ts
- test/__file_snapshots__/issue-365-js.js
- test/__file_snapshots__/loader__styled-interpolations-FancyBox.css
- test/__file_snapshots__/plugin__styled-interpolations-FancyBox.css
this is not as pretty as i'd have hoped but such is life
> fix: styled and single class composes

- README.md
Rollup integration example added with repl, similar to Parcel.
Resolves https://github.com/4Catalyzer/astroturf/issues/111
> Add rollup example to readme

- src/VirtualModulePlugin.ts
> fix: support new webpack watcher API

- www/src/pages/index.tsx
Thanks for Astroturf, seems like a nice option for zero-runtime CSS-in-JS!
Just a quick PR to fix the casing of GitHub
> Fix casing on GitHub

- src/utils/getDisplayName.ts
- test/css-tag.test.js
> feat: use static object properties as identifiers
